# Generated by Django 4.0.4 on 2022-05-29 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.CharField(max_length=70, verbose_name='Название')),
                ('anons', models.CharField(max_length=250, verbose_name='Тема')),
                ('full_text', models.TextField(verbose_name='Текст вопроса')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('rang', models.IntegerField(blank=True, null=True, verbose_name='Рейтинг')),
                ('comp', models.BooleanField(default=False, verbose_name='Решенный')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'db_table': 'que',
            },
        ),
    ]
